server:
  port: ${PORT:8081}   # Render에서 제공하는 포트

spring:
  datasource:
    url: jdbc:mysql://182.231.48.148/board?serverTimezone=Asia/Seoul
    username: board_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # 이미 SQL에서 테이블 생성했으므로 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

